# Generated by Django 4.2.7 on 2023-12-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Não-Binário', 'Não-Binário'), ('Prefiro Não Informar', 'Prefiro Não Informar')], max_length=20),
        ),
    ]
